version: '3.7'

services:
  database:
    container_name: qdm_db
    image: postgres:15.7
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: admin_qdmedia
      POSTGRES_DB: qdmedia_db
      POSTGRES_PASSWORD: 1931a38f-62b6-49f4-8d07-5d020a9eb104
      POSTGRES_PORT: 5432
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./popul_tables.sql:/docker-entrypoint-initdb.d/popul_tables.sql
    ports:
      - "5432:5432"
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-size: "20m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 512M

volumes:
  database_data:
    driver: local


